CREATE TABLE IF NOT EXISTS BACKEND.ORDERS(
    ID INT AUTO_INCREMENT,
    MEMBER_ID LONG,
    ADDRESS_ID LONG,
    TOTAL_PRICE DOUBLE,
    TOTAL_SHIPPING DOUBLE,
    TOTAL_TAX DOUBLE,
    TOTAL_SHIPPING_TAX DOUBLE,
    CURRENCY VARCHAR(5),
    STATUS VARCHAR(3),
    TIME_PLACED DATE,
    TIME_UPDATE DATE,
    PRIMARY KEY (ID)
);

ALTER TABLE BACKEND.ORDERS AUTO_INCREMENT=3001;


CREATE TABLE IF NOT EXISTS BACKEND.ORDERITEMS(
    ID INT AUTO_INCREMENT,
    ORDERS_ID INT,
    MEMBER_ID LONG,
    ADDRESS_ID LONG,
    PRODUCT_ID VARCHAR(255),
    PRICE DOUBLE,
    SHIPPING_CHARGE DOUBLE,
    TAX DOUBLE,
    SHIPPING_TAX DOUBLE,
    CURRENCY VARCHAR(5),
    QUANTITY LONG,
    STATUS VARCHAR(3),
    TIME_PLACED DATE,
    TIME_UPDATE DATE,
    PRIMARY KEY (ID),
    CONSTRAINT FK_ORDER FOREIGN KEY (ORDERS_ID) REFERENCES BACKEND.ORDERS(ID)
);


ALTER TABLE BACKEND.ORDERITEMS AUTO_INCREMENT=4001;

commit;
