spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch-cluster
      cluster-nodes: "35.227.16.246:9300"

keyword-search.allowed-pattern: "[^*?]+"


---
spring:
  profiles: docker
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: "elasticsearch:9300"
